### ISSUE TITLE
Php 7 Support?

### ISSUE THREAD

**Issue by IamSwap** [usaepay/usaepay-php#4]
Getting error while using php 7. `preg_replace(): The /e modifier is no longer supported, use preg_replace_callback instead`. By further digging, problem is this method.

``` php
function xmlentities($string)
{
    $string = preg_replace('/[^a-zA-Z0-9 _\-\.\'\r\n]/e', '_uePhpLibPrivateXMLEntities("$0")', $string);
    return $string;
}
```

But by changing method to following, fixes the problem with php7. But not sure if it's safe.

``` php
function xmlentities($string)
{
    $string = preg_replace_callback('[^a-zA-Z0-9 _\-\.\'\r\n]', function($matches) {
        return '_uePhpLibPrivateXMLEntities("$matches[1]")';
    }, $string);
    return $string;
}
```

Any help?

**Comment by ajbonner** [comment]
It can be fixed by using preg_replace_callback, and dropping the /e modifier.

``` php
 $string = preg_replace_callback('/[^a-zA-Z0-9 _\-\.\'\r\n]/', '_uePhpLibPrivateXMLEntities("$0")', $string);
```
